spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: diagnostic_system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://ep-bitter-waterfall-aob26o8j-pooler.c-2.ap-southeast-1.aws.neon.tech/medical_assistance?user=neondb_owner&password=npg_Df2vp4GKIlOQ&sslmode=require&channelBinding=require"
    username: neondb_owner